#ifndef NETWORK_H_INSTRUCTIONS_H_
#define NETWORK_H_INSTRUCTIONS_H_

enum class Instruction {
	STORE_INSTR = 1,
	COLLECT_INSTR = 2,
	RETRV_INSTR = 3,
	JOIN_INSTR = 4,
	SAVE_PARITY = 5
};


#endif /* NETWORK_H_INSTRUCTIONS_H_ */
